/*----------------------------------------------------------------------------*\
|Contains OpenGL declarations used when building the capture DLL               |
|                                                                              |
|Stewart Hall                                                                  |
|12/2/2012                                                                     |
\*----------------------------------------------------------------------------*/

#define EXTERN_DLL_EXPORT extern "C" __declspec(dllexport)

typedef unsigned int GLenum;
typedef unsigned char GLboolean;
typedef unsigned int GLbitfield;
typedef signed char GLbyte;
typedef short GLshort;
typedef int GLint;
typedef int GLsizei;
typedef unsigned char GLubyte;
typedef unsigned short GLushort;
typedef unsigned int GLuint;
typedef float GLfloat;
typedef float GLclampf;
typedef double GLdouble;
typedef double GLclampd;
typedef void GLvoid;

#define TRUE 1
#define FALSE 0
#define NULL 0
#define VOID void

typedef int BOOL;
typedef unsigned int SOCKET;
typedef unsigned int UINT;
typedef int (__stdcall *PROC)();
typedef const char* LPCSTR;
typedef unsigned long DWORD;

#define DECLARE_HANDLE(name) struct name##__ { int unused; }; typedef struct name##__ *name
DECLARE_HANDLE(HDC);
DECLARE_HANDLE(HGLRC);

EXTERN_DLL_EXPORT BOOL wglCopyContext(HGLRC, HGLRC, UINT);
EXTERN_DLL_EXPORT HGLRC wglCreateContext(HDC);
EXTERN_DLL_EXPORT HGLRC wglCreateLayerContext(HDC, int);
EXTERN_DLL_EXPORT BOOL wglDeleteContext(HGLRC);
EXTERN_DLL_EXPORT HGLRC wglGetCurrentContext(VOID);
EXTERN_DLL_EXPORT HDC wglGetCurrentDC(VOID);
EXTERN_DLL_EXPORT PROC wglGetProcAddress(LPCSTR);
EXTERN_DLL_EXPORT BOOL wglMakeCurrent(HDC, HGLRC);
EXTERN_DLL_EXPORT BOOL wglShareLists(HGLRC, HGLRC);
EXTERN_DLL_EXPORT BOOL wglUseFontBitmapsA(HDC, DWORD, DWORD, DWORD);
EXTERN_DLL_EXPORT BOOL wglUseFontBitmapsW(HDC, DWORD, DWORD, DWORD);

EXTERN_DLL_EXPORT void glAccum (GLenum op, GLfloat value);
EXTERN_DLL_EXPORT void glAlphaFunc (GLenum func, GLclampf ref);
EXTERN_DLL_EXPORT GLboolean glAreTexturesResident (GLsizei n, const GLuint *textures, GLboolean *residences);
EXTERN_DLL_EXPORT void glArrayElement (GLint i);
EXTERN_DLL_EXPORT void glBegin (GLenum mode);
EXTERN_DLL_EXPORT void glBindTexture (GLenum target, GLuint texture);
EXTERN_DLL_EXPORT void glBitmap (GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap);
EXTERN_DLL_EXPORT void glBlendFunc (GLenum sfactor, GLenum dfactor);
EXTERN_DLL_EXPORT void glCallList (GLuint list);
EXTERN_DLL_EXPORT void glCallLists (GLsizei n, GLenum type, const GLvoid *lists);
EXTERN_DLL_EXPORT void glClear (GLbitfield mask);
EXTERN_DLL_EXPORT void glClearAccum (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
EXTERN_DLL_EXPORT void glClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
EXTERN_DLL_EXPORT void glClearDepth (GLclampd depth);
EXTERN_DLL_EXPORT void glClearIndex (GLfloat c);
EXTERN_DLL_EXPORT void glClearStencil (GLint s);
EXTERN_DLL_EXPORT void glClipPlane (GLenum plane, const GLdouble *equation);
EXTERN_DLL_EXPORT void glColor3b (GLbyte red, GLbyte green, GLbyte blue);
EXTERN_DLL_EXPORT void glColor3bv (const GLbyte *v);
EXTERN_DLL_EXPORT void glColor3d (GLdouble red, GLdouble green, GLdouble blue);
EXTERN_DLL_EXPORT void glColor3dv (const GLdouble *v);
EXTERN_DLL_EXPORT void glColor3f (GLfloat red, GLfloat green, GLfloat blue);
EXTERN_DLL_EXPORT void glColor3fv (const GLfloat *v);
EXTERN_DLL_EXPORT void glColor3i (GLint red, GLint green, GLint blue);
EXTERN_DLL_EXPORT void glColor3iv (const GLint *v);
EXTERN_DLL_EXPORT void glColor3s (GLshort red, GLshort green, GLshort blue);
EXTERN_DLL_EXPORT void glColor3sv (const GLshort *v);
EXTERN_DLL_EXPORT void glColor3ub (GLubyte red, GLubyte green, GLubyte blue);
EXTERN_DLL_EXPORT void glColor3ubv (const GLubyte *v);
EXTERN_DLL_EXPORT void glColor3ui (GLuint red, GLuint green, GLuint blue);
EXTERN_DLL_EXPORT void glColor3uiv (const GLuint *v);
EXTERN_DLL_EXPORT void glColor3us (GLushort red, GLushort green, GLushort blue);
EXTERN_DLL_EXPORT void glColor3usv (const GLushort *v);
EXTERN_DLL_EXPORT void glColor4b (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha);
EXTERN_DLL_EXPORT void glColor4bv (const GLbyte *v);
EXTERN_DLL_EXPORT void glColor4d (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha);
EXTERN_DLL_EXPORT void glColor4dv (const GLdouble *v);
EXTERN_DLL_EXPORT void glColor4f (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
EXTERN_DLL_EXPORT void glColor4fv (const GLfloat *v);
EXTERN_DLL_EXPORT void glColor4i (GLint red, GLint green, GLint blue, GLint alpha);
EXTERN_DLL_EXPORT void glColor4iv (const GLint *v);
EXTERN_DLL_EXPORT void glColor4s (GLshort red, GLshort green, GLshort blue, GLshort alpha);
EXTERN_DLL_EXPORT void glColor4sv (const GLshort *v);
EXTERN_DLL_EXPORT void glColor4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
EXTERN_DLL_EXPORT void glColor4ubv (const GLubyte *v);
EXTERN_DLL_EXPORT void glColor4ui (GLuint red, GLuint green, GLuint blue, GLuint alpha);
EXTERN_DLL_EXPORT void glColor4uiv (const GLuint *v);
EXTERN_DLL_EXPORT void glColor4us (GLushort red, GLushort green, GLushort blue, GLushort alpha);
EXTERN_DLL_EXPORT void glColor4usv (const GLushort *v);
EXTERN_DLL_EXPORT void glColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
EXTERN_DLL_EXPORT void glColorMaterial (GLenum face, GLenum mode);
EXTERN_DLL_EXPORT void glColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
EXTERN_DLL_EXPORT void glCopyPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum type);
EXTERN_DLL_EXPORT void glCopyTexImage1D (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border);
EXTERN_DLL_EXPORT void glCopyTexImage2D (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
EXTERN_DLL_EXPORT void glCopyTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
EXTERN_DLL_EXPORT void glCopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
EXTERN_DLL_EXPORT void glCullFace (GLenum mode);
EXTERN_DLL_EXPORT void glDeleteLists (GLuint list, GLsizei range);
EXTERN_DLL_EXPORT void glDeleteTextures (GLsizei n, const GLuint *textures);
EXTERN_DLL_EXPORT void glDepthFunc (GLenum func);
EXTERN_DLL_EXPORT void glDepthMask (GLboolean flag);
EXTERN_DLL_EXPORT void glDepthRange (GLclampd zNear, GLclampd zFar);
EXTERN_DLL_EXPORT void glDisable (GLenum cap);
EXTERN_DLL_EXPORT void glDisableClientState (GLenum array);
EXTERN_DLL_EXPORT void glDrawArrays (GLenum mode, GLint first, GLsizei count);
EXTERN_DLL_EXPORT void glDrawBuffer (GLenum mode);
EXTERN_DLL_EXPORT void glDrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices);
EXTERN_DLL_EXPORT void glDrawPixels (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
EXTERN_DLL_EXPORT void glEdgeFlag (GLboolean flag);
EXTERN_DLL_EXPORT void glEdgeFlagPointer (GLsizei stride, const GLvoid *pointer);
EXTERN_DLL_EXPORT void glEdgeFlagv (const GLboolean *flag);
EXTERN_DLL_EXPORT void glEnable (GLenum cap);
EXTERN_DLL_EXPORT void glEnableClientState (GLenum array);
EXTERN_DLL_EXPORT void glEnd (void);
EXTERN_DLL_EXPORT void glEndList (void);
EXTERN_DLL_EXPORT void glEvalCoord1d (GLdouble u);
EXTERN_DLL_EXPORT void glEvalCoord1dv (const GLdouble *u);
EXTERN_DLL_EXPORT void glEvalCoord1f (GLfloat u);
EXTERN_DLL_EXPORT void glEvalCoord1fv (const GLfloat *u);
EXTERN_DLL_EXPORT void glEvalCoord2d (GLdouble u, GLdouble v);
EXTERN_DLL_EXPORT void glEvalCoord2dv (const GLdouble *u);
EXTERN_DLL_EXPORT void glEvalCoord2f (GLfloat u, GLfloat v);
EXTERN_DLL_EXPORT void glEvalCoord2fv (const GLfloat *u);
EXTERN_DLL_EXPORT void glEvalMesh1 (GLenum mode, GLint i1, GLint i2);
EXTERN_DLL_EXPORT void glEvalMesh2 (GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2);
EXTERN_DLL_EXPORT void glEvalPoint1 (GLint i);
EXTERN_DLL_EXPORT void glEvalPoint2 (GLint i, GLint j);
EXTERN_DLL_EXPORT void glFeedbackBuffer (GLsizei size, GLenum type, GLfloat *buffer);
EXTERN_DLL_EXPORT void glFinish (void);
EXTERN_DLL_EXPORT void glFlush (void);
EXTERN_DLL_EXPORT void glFogf (GLenum pname, GLfloat param);
EXTERN_DLL_EXPORT void glFogfv (GLenum pname, const GLfloat *params);
EXTERN_DLL_EXPORT void glFogi (GLenum pname, GLint param);
EXTERN_DLL_EXPORT void glFogiv (GLenum pname, const GLint *params);
EXTERN_DLL_EXPORT void glFrontFace (GLenum mode);
EXTERN_DLL_EXPORT void glFrustum (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
EXTERN_DLL_EXPORT GLuint glGenLists (GLsizei range);
EXTERN_DLL_EXPORT void glGenTextures (GLsizei n, GLuint *textures);
EXTERN_DLL_EXPORT void glGetBooleanv (GLenum pname, GLboolean *params);
EXTERN_DLL_EXPORT void glGetClipPlane (GLenum plane, GLdouble *equation);
EXTERN_DLL_EXPORT void glGetDoublev (GLenum pname, GLdouble *params);
EXTERN_DLL_EXPORT GLenum glGetError (void);
EXTERN_DLL_EXPORT void glGetFloatv (GLenum pname, GLfloat *params);
EXTERN_DLL_EXPORT void glGetIntegerv (GLenum pname, GLint *params);
EXTERN_DLL_EXPORT void glGetLightfv (GLenum light, GLenum pname, GLfloat *params);
EXTERN_DLL_EXPORT void glGetLightiv (GLenum light, GLenum pname, GLint *params);
EXTERN_DLL_EXPORT void glGetMapdv (GLenum target, GLenum query, GLdouble *v);
EXTERN_DLL_EXPORT void glGetMapfv (GLenum target, GLenum query, GLfloat *v);
EXTERN_DLL_EXPORT void glGetMapiv (GLenum target, GLenum query, GLint *v);
EXTERN_DLL_EXPORT void glGetMaterialfv (GLenum face, GLenum pname, GLfloat *params);
EXTERN_DLL_EXPORT void glGetMaterialiv (GLenum face, GLenum pname, GLint *params);
EXTERN_DLL_EXPORT void glGetPixelMapfv (GLenum map, GLfloat *values);
EXTERN_DLL_EXPORT void glGetPixelMapuiv (GLenum map, GLuint *values);
EXTERN_DLL_EXPORT void glGetPixelMapusv (GLenum map, GLushort *values);
EXTERN_DLL_EXPORT void glGetPointerv (GLenum pname, GLvoid* *params);
EXTERN_DLL_EXPORT void glGetPolygonStipple (GLubyte *mask);  
EXTERN_DLL_EXPORT const GLubyte * glGetString(GLenum name);
EXTERN_DLL_EXPORT void glGetTexEnvfv (GLenum target, GLenum pname, GLfloat *params);
EXTERN_DLL_EXPORT void glGetTexEnviv (GLenum target, GLenum pname, GLint *params);
EXTERN_DLL_EXPORT void glGetTexGendv (GLenum coord, GLenum pname, GLdouble *params);
EXTERN_DLL_EXPORT void glGetTexGenfv (GLenum coord, GLenum pname, GLfloat *params);
EXTERN_DLL_EXPORT void glGetTexGeniv (GLenum coord, GLenum pname, GLint *params);
EXTERN_DLL_EXPORT void glGetTexImage (GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels);
EXTERN_DLL_EXPORT void glGetTexLevelParameterfv (GLenum target, GLint level, GLenum pname, GLfloat *params);
EXTERN_DLL_EXPORT void glGetTexLevelParameteriv (GLenum target, GLint level, GLenum pname, GLint *params);
EXTERN_DLL_EXPORT void glGetTexParameterfv (GLenum target, GLenum pname, GLfloat *params);
EXTERN_DLL_EXPORT void glGetTexParameteriv (GLenum target, GLenum pname, GLint *params);
EXTERN_DLL_EXPORT void glHint (GLenum target, GLenum mode);
EXTERN_DLL_EXPORT void glIndexMask (GLuint mask);
EXTERN_DLL_EXPORT void glIndexPointer (GLenum type, GLsizei stride, const GLvoid *pointer);
EXTERN_DLL_EXPORT void glIndexd (GLdouble c);
EXTERN_DLL_EXPORT void glIndexdv (const GLdouble *c);
EXTERN_DLL_EXPORT void glIndexf (GLfloat c);
EXTERN_DLL_EXPORT void glIndexfv (const GLfloat *c);
EXTERN_DLL_EXPORT void glIndexi (GLint c);
EXTERN_DLL_EXPORT void glIndexiv (const GLint *c);
EXTERN_DLL_EXPORT void glIndexs (GLshort c);
EXTERN_DLL_EXPORT void glIndexsv (const GLshort *c);
EXTERN_DLL_EXPORT void glIndexub (GLubyte c);
EXTERN_DLL_EXPORT void glIndexubv (const GLubyte *c);
EXTERN_DLL_EXPORT void glInitNames (void);
EXTERN_DLL_EXPORT void glInterleavedArrays (GLenum format, GLsizei stride, const GLvoid *pointer);
EXTERN_DLL_EXPORT GLboolean glIsEnabled (GLenum cap);
EXTERN_DLL_EXPORT GLboolean glIsList (GLuint list);
EXTERN_DLL_EXPORT GLboolean glIsTexture (GLuint texture);
EXTERN_DLL_EXPORT void glLightModelf (GLenum pname, GLfloat param);
EXTERN_DLL_EXPORT void glLightModelfv (GLenum pname, const GLfloat *params);
EXTERN_DLL_EXPORT void glLightModeli (GLenum pname, GLint param);
EXTERN_DLL_EXPORT void glLightModeliv (GLenum pname, const GLint *params);
EXTERN_DLL_EXPORT void glLightf (GLenum light, GLenum pname, GLfloat param);
EXTERN_DLL_EXPORT void glLightfv (GLenum light, GLenum pname, const GLfloat *params);
EXTERN_DLL_EXPORT void glLighti (GLenum light, GLenum pname, GLint param);
EXTERN_DLL_EXPORT void glLightiv (GLenum light, GLenum pname, const GLint *params);
EXTERN_DLL_EXPORT void glLineStipple (GLint factor, GLushort pattern);
EXTERN_DLL_EXPORT void glLineWidth (GLfloat width);
EXTERN_DLL_EXPORT void glListBase (GLuint base);
EXTERN_DLL_EXPORT void glLoadIdentity (void);
EXTERN_DLL_EXPORT void glLoadMatrixd (const GLdouble *m);
EXTERN_DLL_EXPORT void glLoadMatrixf (const GLfloat *m);
EXTERN_DLL_EXPORT void glLoadName (GLuint name);
EXTERN_DLL_EXPORT void glLogicOp (GLenum opcode);
EXTERN_DLL_EXPORT void glMap1d (GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points);
EXTERN_DLL_EXPORT void glMap1f (GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points);
EXTERN_DLL_EXPORT void glMap2d (GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points);
EXTERN_DLL_EXPORT void glMap2f (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points);
EXTERN_DLL_EXPORT void glMapGrid1d (GLint un, GLdouble u1, GLdouble u2);
EXTERN_DLL_EXPORT void glMapGrid1f (GLint un, GLfloat u1, GLfloat u2);
EXTERN_DLL_EXPORT void glMapGrid2d (GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2);
EXTERN_DLL_EXPORT void glMapGrid2f (GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2);
EXTERN_DLL_EXPORT void glMaterialf (GLenum face, GLenum pname, GLfloat param);
EXTERN_DLL_EXPORT void glMaterialfv (GLenum face, GLenum pname, const GLfloat *params);
EXTERN_DLL_EXPORT void glMateriali (GLenum face, GLenum pname, GLint param);
EXTERN_DLL_EXPORT void glMaterialiv (GLenum face, GLenum pname, const GLint *params);
EXTERN_DLL_EXPORT void glMatrixMode (GLenum mode);
EXTERN_DLL_EXPORT void glMultMatrixd (const GLdouble *m);
EXTERN_DLL_EXPORT void glMultMatrixf (const GLfloat *m);
EXTERN_DLL_EXPORT void glNewList (GLuint list, GLenum mode);
EXTERN_DLL_EXPORT void glNormal3b (GLbyte nx, GLbyte ny, GLbyte nz);
EXTERN_DLL_EXPORT void glNormal3bv (const GLbyte *v);
EXTERN_DLL_EXPORT void glNormal3d (GLdouble nx, GLdouble ny, GLdouble nz);
EXTERN_DLL_EXPORT void glNormal3dv (const GLdouble *v);
EXTERN_DLL_EXPORT void glNormal3f (GLfloat nx, GLfloat ny, GLfloat nz);
EXTERN_DLL_EXPORT void glNormal3fv (const GLfloat *v);
EXTERN_DLL_EXPORT void glNormal3i (GLint nx, GLint ny, GLint nz);
EXTERN_DLL_EXPORT void glNormal3iv (const GLint *v);
EXTERN_DLL_EXPORT void glNormal3s (GLshort nx, GLshort ny, GLshort nz);
EXTERN_DLL_EXPORT void glNormal3sv (const GLshort *v);
EXTERN_DLL_EXPORT void glNormalPointer (GLenum type, GLsizei stride, const GLvoid *pointer);
EXTERN_DLL_EXPORT void glOrtho (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
EXTERN_DLL_EXPORT void glPassThrough (GLfloat token);
EXTERN_DLL_EXPORT void glPixelMapfv (GLenum map, GLsizei mapsize, const GLfloat *values);
EXTERN_DLL_EXPORT void glPixelMapuiv (GLenum map, GLsizei mapsize, const GLuint *values);
EXTERN_DLL_EXPORT void glPixelMapusv (GLenum map, GLsizei mapsize, const GLushort *values);
EXTERN_DLL_EXPORT void glPixelStoref (GLenum pname, GLfloat param);
EXTERN_DLL_EXPORT void glPixelStorei (GLenum pname, GLint param);
EXTERN_DLL_EXPORT void glPixelTransferf (GLenum pname, GLfloat param);
EXTERN_DLL_EXPORT void glPixelTransferi (GLenum pname, GLint param);
EXTERN_DLL_EXPORT void glPixelZoom (GLfloat xfactor, GLfloat yfactor);
EXTERN_DLL_EXPORT void glPointSize (GLfloat size);
EXTERN_DLL_EXPORT void glPolygonMode (GLenum face, GLenum mode);
EXTERN_DLL_EXPORT void glPolygonOffset (GLfloat factor, GLfloat units);
EXTERN_DLL_EXPORT void glPolygonStipple (const GLubyte *mask);
EXTERN_DLL_EXPORT void glPopAttrib (void);
EXTERN_DLL_EXPORT void glPopClientAttrib (void);
EXTERN_DLL_EXPORT void glPopMatrix (void);
EXTERN_DLL_EXPORT void glPopName (void);
EXTERN_DLL_EXPORT void glPrioritizeTextures (GLsizei n, const GLuint *textures, const GLclampf *priorities);
EXTERN_DLL_EXPORT void glPushAttrib (GLbitfield mask);
EXTERN_DLL_EXPORT void glPushClientAttrib (GLbitfield mask);
EXTERN_DLL_EXPORT void glPushMatrix (void);
EXTERN_DLL_EXPORT void glPushName (GLuint name);
EXTERN_DLL_EXPORT void glRasterPos2d (GLdouble x, GLdouble y);
EXTERN_DLL_EXPORT void glRasterPos2dv (const GLdouble *v);
EXTERN_DLL_EXPORT void glRasterPos2f (GLfloat x, GLfloat y);
EXTERN_DLL_EXPORT void glRasterPos2fv (const GLfloat *v);
EXTERN_DLL_EXPORT void glRasterPos2i (GLint x, GLint y);
EXTERN_DLL_EXPORT void glRasterPos2iv (const GLint *v);
EXTERN_DLL_EXPORT void glRasterPos2s (GLshort x, GLshort y);
EXTERN_DLL_EXPORT void glRasterPos2sv (const GLshort *v);
EXTERN_DLL_EXPORT void glRasterPos3d (GLdouble x, GLdouble y, GLdouble z);
EXTERN_DLL_EXPORT void glRasterPos3dv (const GLdouble *v);
EXTERN_DLL_EXPORT void glRasterPos3f (GLfloat x, GLfloat y, GLfloat z);
EXTERN_DLL_EXPORT void glRasterPos3fv (const GLfloat *v);
EXTERN_DLL_EXPORT void glRasterPos3i (GLint x, GLint y, GLint z);
EXTERN_DLL_EXPORT void glRasterPos3iv (const GLint *v);
EXTERN_DLL_EXPORT void glRasterPos3s (GLshort x, GLshort y, GLshort z);
EXTERN_DLL_EXPORT void glRasterPos3sv (const GLshort *v);
EXTERN_DLL_EXPORT void glRasterPos4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w);
EXTERN_DLL_EXPORT void glRasterPos4dv (const GLdouble *v);
EXTERN_DLL_EXPORT void glRasterPos4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w);
EXTERN_DLL_EXPORT void glRasterPos4fv (const GLfloat *v);
EXTERN_DLL_EXPORT void glRasterPos4i (GLint x, GLint y, GLint z, GLint w);
EXTERN_DLL_EXPORT void glRasterPos4iv (const GLint *v);
EXTERN_DLL_EXPORT void glRasterPos4s (GLshort x, GLshort y, GLshort z, GLshort w);
EXTERN_DLL_EXPORT void glRasterPos4sv (const GLshort *v);
EXTERN_DLL_EXPORT void glReadBuffer (GLenum mode);
EXTERN_DLL_EXPORT void glReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels);
EXTERN_DLL_EXPORT void glRectd (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2);
EXTERN_DLL_EXPORT void glRectdv (const GLdouble *v1, const GLdouble *v2);
EXTERN_DLL_EXPORT void glRectf (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2);
EXTERN_DLL_EXPORT void glRectfv (const GLfloat *v1, const GLfloat *v2);
EXTERN_DLL_EXPORT void glRecti (GLint x1, GLint y1, GLint x2, GLint y2);
EXTERN_DLL_EXPORT void glRectiv (const GLint *v1, const GLint *v2);
EXTERN_DLL_EXPORT void glRects (GLshort x1, GLshort y1, GLshort x2, GLshort y2);
EXTERN_DLL_EXPORT void glRectsv (const GLshort *v1, const GLshort *v2);
EXTERN_DLL_EXPORT GLint glRenderMode (GLenum mode);
EXTERN_DLL_EXPORT void glRotated (GLdouble angle, GLdouble x, GLdouble y, GLdouble z);
EXTERN_DLL_EXPORT void glRotatef (GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
EXTERN_DLL_EXPORT void glScaled (GLdouble x, GLdouble y, GLdouble z);
EXTERN_DLL_EXPORT void glScalef (GLfloat x, GLfloat y, GLfloat z);
EXTERN_DLL_EXPORT void glScissor (GLint x, GLint y, GLsizei width, GLsizei height);
EXTERN_DLL_EXPORT void glSelectBuffer (GLsizei size, GLuint *buffer);
EXTERN_DLL_EXPORT void glShadeModel (GLenum mode);
EXTERN_DLL_EXPORT void glStencilFunc (GLenum func, GLint ref, GLuint mask);
EXTERN_DLL_EXPORT void glStencilMask (GLuint mask);
EXTERN_DLL_EXPORT void glStencilOp (GLenum fail, GLenum zfail, GLenum zpass);
EXTERN_DLL_EXPORT void glTexCoord1d (GLdouble s);
EXTERN_DLL_EXPORT void glTexCoord1dv (const GLdouble *v);
EXTERN_DLL_EXPORT void glTexCoord1f (GLfloat s);
EXTERN_DLL_EXPORT void glTexCoord1fv (const GLfloat *v);
EXTERN_DLL_EXPORT void glTexCoord1i (GLint s);
EXTERN_DLL_EXPORT void glTexCoord1iv (const GLint *v);
EXTERN_DLL_EXPORT void glTexCoord1s (GLshort s);
EXTERN_DLL_EXPORT void glTexCoord1sv (const GLshort *v);
EXTERN_DLL_EXPORT void glTexCoord2d (GLdouble s, GLdouble t);
EXTERN_DLL_EXPORT void glTexCoord2dv (const GLdouble *v);
EXTERN_DLL_EXPORT void glTexCoord2f (GLfloat s, GLfloat t);
EXTERN_DLL_EXPORT void glTexCoord2fv (const GLfloat *v);
EXTERN_DLL_EXPORT void glTexCoord2i (GLint s, GLint t);
EXTERN_DLL_EXPORT void glTexCoord2iv (const GLint *v);
EXTERN_DLL_EXPORT void glTexCoord2s (GLshort s, GLshort t);
EXTERN_DLL_EXPORT void glTexCoord2sv (const GLshort *v);
EXTERN_DLL_EXPORT void glTexCoord3d (GLdouble s, GLdouble t, GLdouble r);
EXTERN_DLL_EXPORT void glTexCoord3dv (const GLdouble *v);
EXTERN_DLL_EXPORT void glTexCoord3f (GLfloat s, GLfloat t, GLfloat r);
EXTERN_DLL_EXPORT void glTexCoord3fv (const GLfloat *v);
EXTERN_DLL_EXPORT void glTexCoord3i (GLint s, GLint t, GLint r);
EXTERN_DLL_EXPORT void glTexCoord3iv (const GLint *v);
EXTERN_DLL_EXPORT void glTexCoord3s (GLshort s, GLshort t, GLshort r);
EXTERN_DLL_EXPORT void glTexCoord3sv (const GLshort *v);
EXTERN_DLL_EXPORT void glTexCoord4d (GLdouble s, GLdouble t, GLdouble r, GLdouble q);
EXTERN_DLL_EXPORT void glTexCoord4dv (const GLdouble *v);
EXTERN_DLL_EXPORT void glTexCoord4f (GLfloat s, GLfloat t, GLfloat r, GLfloat q);
EXTERN_DLL_EXPORT void glTexCoord4fv (const GLfloat *v);
EXTERN_DLL_EXPORT void glTexCoord4i (GLint s, GLint t, GLint r, GLint q);
EXTERN_DLL_EXPORT void glTexCoord4iv (const GLint *v);
EXTERN_DLL_EXPORT void glTexCoord4s (GLshort s, GLshort t, GLshort r, GLshort q);
EXTERN_DLL_EXPORT void glTexCoord4sv (const GLshort *v);
EXTERN_DLL_EXPORT void glTexCoordPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
EXTERN_DLL_EXPORT void glTexEnvf (GLenum target, GLenum pname, GLfloat param);
EXTERN_DLL_EXPORT void glTexEnvfv (GLenum target, GLenum pname, const GLfloat *params);
EXTERN_DLL_EXPORT void glTexEnvi (GLenum target, GLenum pname, GLint param);
EXTERN_DLL_EXPORT void glTexEnviv (GLenum target, GLenum pname, const GLint *params);
EXTERN_DLL_EXPORT void glTexGend (GLenum coord, GLenum pname, GLdouble param);
EXTERN_DLL_EXPORT void glTexGendv (GLenum coord, GLenum pname, const GLdouble *params);
EXTERN_DLL_EXPORT void glTexGenf (GLenum coord, GLenum pname, GLfloat param);
EXTERN_DLL_EXPORT void glTexGenfv (GLenum coord, GLenum pname, const GLfloat *params);
EXTERN_DLL_EXPORT void glTexGeni (GLenum coord, GLenum pname, GLint param);
EXTERN_DLL_EXPORT void glTexGeniv (GLenum coord, GLenum pname, const GLint *params);
EXTERN_DLL_EXPORT void glTexImage1D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
EXTERN_DLL_EXPORT void glTexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
EXTERN_DLL_EXPORT void glTexParameterf (GLenum target, GLenum pname, GLfloat param);
EXTERN_DLL_EXPORT void glTexParameterfv (GLenum target, GLenum pname, const GLfloat *params);
EXTERN_DLL_EXPORT void glTexParameteri (GLenum target, GLenum pname, GLint param);
EXTERN_DLL_EXPORT void glTexParameteriv (GLenum target, GLenum pname, const GLint *params);
EXTERN_DLL_EXPORT void glTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels);
EXTERN_DLL_EXPORT void glTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
EXTERN_DLL_EXPORT void glTranslated (GLdouble x, GLdouble y, GLdouble z);
EXTERN_DLL_EXPORT void glTranslatef (GLfloat x, GLfloat y, GLfloat z);
EXTERN_DLL_EXPORT void glVertex2d (GLdouble x, GLdouble y);
EXTERN_DLL_EXPORT void glVertex2dv (const GLdouble *v);
EXTERN_DLL_EXPORT void glVertex2f (GLfloat x, GLfloat y);
EXTERN_DLL_EXPORT void glVertex2fv (const GLfloat *v);
EXTERN_DLL_EXPORT void glVertex2i (GLint x, GLint y);
EXTERN_DLL_EXPORT void glVertex2iv (const GLint *v);
EXTERN_DLL_EXPORT void glVertex2s (GLshort x, GLshort y);
EXTERN_DLL_EXPORT void glVertex2sv (const GLshort *v);
EXTERN_DLL_EXPORT void glVertex3d (GLdouble x, GLdouble y, GLdouble z);
EXTERN_DLL_EXPORT void glVertex3dv (const GLdouble *v);
EXTERN_DLL_EXPORT void glVertex3f (GLfloat x, GLfloat y, GLfloat z);
EXTERN_DLL_EXPORT void glVertex3fv (const GLfloat *v);
EXTERN_DLL_EXPORT void glVertex3i (GLint x, GLint y, GLint z);
EXTERN_DLL_EXPORT void glVertex3iv (const GLint *v);
EXTERN_DLL_EXPORT void glVertex3s (GLshort x, GLshort y, GLshort z);
EXTERN_DLL_EXPORT void glVertex3sv (const GLshort *v);
EXTERN_DLL_EXPORT void glVertex4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w);
EXTERN_DLL_EXPORT void glVertex4dv (const GLdouble *v);
EXTERN_DLL_EXPORT void glVertex4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w);
EXTERN_DLL_EXPORT void glVertex4fv (const GLfloat *v);
EXTERN_DLL_EXPORT void glVertex4i (GLint x, GLint y, GLint z, GLint w);
EXTERN_DLL_EXPORT void glVertex4iv (const GLint *v);
EXTERN_DLL_EXPORT void glVertex4s (GLshort x, GLshort y, GLshort z, GLshort w);
EXTERN_DLL_EXPORT void glVertex4sv (const GLshort *v);
EXTERN_DLL_EXPORT void glVertexPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
EXTERN_DLL_EXPORT void glViewport (GLint x, GLint y, GLsizei width, GLsizei height);
